baseURL = "https://cbielstein.github.io/"
languageCode = "en-us"
title = "Cameron Bielstein"
theme = "hugo-lodi-theme"

disableKinds = ["taxonomy", "term"]

[params]
    theme_color = "#006d00"
    description = "Cameron Bielstein, software engineer"
    description_photo = "share.png"
    favicon = "favicon.png"
    logo = "logo.png"
    twitter = "CBielstein"
    linkedin = "https://www.linkedin.com/in/cameronbielstein/"
    github = "CBielstein"
    googlescholar = "https://scholar.google.com/citations?user=BNIbkwMAAAAJ&hl=en"
    stackoverflow = "https://stackoverflow.com/users/1676364/cameron-bielstein"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.png"
    subtitle = "Hi! I'm Cameron, a software engineer living in Seattle."
    hero_right = [
            "**I'm currently building scientific software for the [Allen Institute for Brain Science](https://alleninstitute.org/what-we-do/brain-science/). Previous work includes [Microsoft](https://www.microsoft.com) and freelance. I received my education from [The University of Texas at Austin](https://www.utexas.edu/) and [Austin Community College](https://www.austincc.edu/)**",
            "I have the following areas of specialty:",
            "* **Web Services**: Former engineer on [Microsoft Azure Digital Twins](https://azure.microsoft.com/en-us/services/digital-twins/), backend developer for the [Allen Brain Map](https://portal.brain-map.org/), and a master's degree from [UT Austin](https://www.utexas.edu/) with a focus in distributed systems.",
            "* **Operating Systems**: Former engineer on [Microsoft Windows](https://www.microsoft.com/en-us/windows) and a [master's thesis](https://repositories.lib.utexas.edu/handle/2152/31851) in secure distributed computing.",
            "* **Wireless Communication**: Developer of the [open source APRS# packet radio project](https://github.com/CBielstein/APRSsharp/) and licensed FCC amateur radio operator.",
            "* **Mentorship**: Mentorship and coaching experience with [Hunt the Wumpus](https://www.lwsd.org/programs-and-services/communications/news/news-details/~board/high-schools/post/lwsd-teams-compete-in-microsofts-hunt-the-wumpus-game-design-competition), [InternLink 2020](http://web.archive.org/web/20210118044239/https://www.internlink.org/), and the Microsoft university internship program."]

[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = false
