baseURL = "https://cbielstein.github.io/"
languageCode = "en-us"
title = "Cameron Bielstein"
theme = "hugo-lodi-theme"

disableKinds = ["taxonomy", "term"]

[params]
    theme_color = "#006d00"
    description = "Cameron Bielstein, software engineer"
    description_photo = "share.png"
    favicon = "favicon.png"
    logo = "logo.png"
    twitter = "CBielstein"
    linkedin = "https://www.linkedin.com/in/cameronbielstein/"
    github = "CBielstein"
    googlescholar = "https://scholar.google.com/citations?user=BNIbkwMAAAAJ&hl=en"
    stackoverflow = "https://stackoverflow.com/users/1676364/cameron-bielstein"
    nuget = "https://www.nuget.org/profiles/CBielstein"
    mastodon = "https://techhub.social/@cbielstein"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.png"
    subtitle = "Hi! I'm Cameron, a software engineer living in Seattle."
    hero_right = [
            "I'm currently building scientific software for the [Allen Institute for Brain Science](https://alleninstitute.org/what-we-do/brain-science/). Previous work includes [Microsoft](https://www.microsoft.com), freelance, and various internships.",
            "I received my education from [The University of Texas at Austin](https://www.utexas.edu/), where I completed a master's in computer science, and [Austin Community College](https://www.austincc.edu/), where I first discovered my love of programming.",
            "I enjoy building high-quality and reliable software and I'm passionate about using technology and technology companies for societal good.",
            "In my spare time, I can be found sailing, tinkering with a ham radio, or in the park with my dog."]

[params.specialties]
    enable = true
    title = "Specialties"
    subtitle = "Areas of Experience"

[params.projects]
    enable = true
    title = "Projects"
    subtitle = "Open Source and Personal Projects"

[params.skills]
    enable = true
    title = "Skills"
    subtitle = ""

[params.publications_and_talks]
    enable = true
    title = "Professional Communication"
    subtitle = "Talks and Publications"
    index_limit = 5
    limit = 10000

[params.timeline]
    enable = true
    title = "Timeline"
    subtitle = "Career Timeline"
    index_timeline_limit = 5
    timeline_limit = 10000

[params.footer]
    enable = true
