baseURL = "localhost:1313"
languageCode = "en-us"
title = "My Portfolio Website"
theme = "hugo-lodi-theme"

[params]
    # head theme color
    theme_color = 

    # head description
    # This is what appears on the preview when posting this site on Facebook for example
    description = "Portfolio of Alexis Collado, UX Designer"

    # head photo
    # This is what appears on the preview when posting this site on Facebook for example
    description_photo = "portfolio.jpg"

    # favicon image (512x512px), place this in the static/img folder
    favicon = "favicon.jpg"

    # logo image (204x204px), place this in the static/img folder
    # this appears on the top left of the navigation
    logo = "logo.jpg"

    # Email
    email = ""

    # Facebook username
    facebook = ""

    # Twitter username
    twitter = ""

    # Dribbble username
    dribbble = ""

    # LinkedIn URL
    linkedin = ""
    
    # Medium username
    medium = ""

[params.nav]
    enable = true

[params.hero]
    enable = true
    
    # Place this image in the static/img folder
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Alexis, a UX Designer and Evangelist from Manila."

    # Each element in this array makes a new <p> tag
    # You can write this text in markdown
    hero_right = [
    "**Currently doing consultancy work at UX Society. Previously doing UX and product at Agoda in Bangkok, Thailand as an international intern.**",
    "I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.",
    "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.",
    "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).",
    "I'm finishing my Bachelor's degree in Management Information Systems at the Ateneo de Manila University, expecting to graduate in 2018."]

    # Link to your resume, place your PDF in the /static folder
    resume = "ResumeCollado.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
